<a href="https://colab.research.google.com/github/sivaramanrajagopal/myNLP60dayprogress/blob/main/Day16_23022022_NLP_Text_Classificationproject_Covid_tweet_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
upload=files.upload()

Saving Corona_NLP_train.csv to Corona_NLP_train.csv


In [ ]:
df= pd.read_csv("Corona_NLP_train.csv",encoding='latin-1')

In [ ]:
df.head()

UserName  ...           Sentiment
0      3799  ...             Neutral
1      3800  ...            Positive
2      3801  ...            Positive
3      3802  ...            Positive
4      3803  ...  Extremely Negative

[5 rows x 6 columns]

In [ ]:
len(df)

41157

In [ ]:
print(df['OriginalTweet'][0])

@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/iFz9FAn2Pa and https://t.co/xX6ghGFzCC and https://t.co/I2NlzdxNo8


In [ ]:
df.isnull().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

UserName         0
ScreenName       0
Location         0
TweetAt          0
OriginalTweet    0
Sentiment        0
dtype: int64

In [ ]:
blanks= []
for i,UN,SN,LC,TW,OT,SN in df.itertuples():
  if OT.isspace():
    blanks.append(i)
    


In [ ]:
blanks

[]

In [ ]:
df.drop(blanks,inplace=True)

In [ ]:
len(df)

32567

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df['OriginalTweet']

In [ ]:
y = df['Sentiment']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.30, random_state=42)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC


In [ ]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),
                     ('clf',LinearSVC())])

In [ ]:
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [ ]:
X_test

17683    Small businesses, especially those that rely o...
38633    covid-19 got us all jopping...jobless n shoppi...
6146     Convenience Store Retail Chain @YeswayStores M...
30664    “It amounts to an estimated $25 billion in sa...
6742     @VBadawey @fordnation  @JustinTrudeau @HydroOn...
                               ...                        
39605    When there’s no queue at the supermarket and ...
18839    @RajatSharmaLive @narendramodi Rajat Jee ppl a...
26020    Another bumper lot of donations at the Addisco...
26087    National emergencies can be disastrous for U.S...
30477    This is the moment to not be going to the groc...
Name: OriginalTweet, Length: 9771, dtype: object

In [ ]:
predictions = text_clf.predict(X_test)

In [ ]:
X_test

17683    Small businesses, especially those that rely o...
38633    covid-19 got us all jopping...jobless n shoppi...
6146     Convenience Store Retail Chain @YeswayStores M...
30664    “It amounts to an estimated $25 billion in sa...
6742     @VBadawey @fordnation  @JustinTrudeau @HydroOn...
                               ...                        
39605    When there’s no queue at the supermarket and ...
18839    @RajatSharmaLive @narendramodi Rajat Jee ppl a...
26020    Another bumper lot of donations at the Addisco...
26087    National emergencies can be disastrous for U.S...
30477    This is the moment to not be going to the groc...
Name: OriginalTweet, Length: 9771, dtype: object

In [ ]:
y_test

17683              Negative
38633               Neutral
6146     Extremely Positive
30664              Negative
6742                Neutral
                ...        
39605              Negative
18839    Extremely Positive
26020              Negative
26087    Extremely Positive
30477    Extremely Positive
Name: Sentiment, Length: 9771, dtype: object

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [ ]:
print(confusion_matrix(y_test,predictions))

[[ 794   14  383   32   67]
 [  11 1011   55   37  452]
 [ 402   78 1035  326  479]
 [  40   30  259 1124  384]
 [  71  581  406  350 1350]]


In [ ]:
print(classification_report(y_test,predictions))

                    precision    recall  f1-score   support

Extremely Negative       0.60      0.62      0.61      1290
Extremely Positive       0.59      0.65      0.62      1566
          Negative       0.48      0.45      0.46      2320
           Neutral       0.60      0.61      0.61      1837
          Positive       0.49      0.49      0.49      2758

          accuracy                           0.54      9771
         macro avg       0.55      0.56      0.56      9771
      weighted avg       0.54      0.54      0.54      9771



In [ ]:
print(accuracy_score(y_test,predictions))

0.5438542626138574


In [ ]:
# real review from internet
text_clf.predict(["Covid 19 spead in Asia is considerably low"])

array(['Negative'], dtype=object)

In [ ]:
df["Sentiment"].value_counts()

Positive              9110
Negative              7763
Neutral               6172
Extremely Positive    5273
Extremely Negative    4249
Name: Sentiment, dtype: int64

In [ ]:
from google.colab import files
upload=files.upload()

Saving Corona_NLP_test.csv to Corona_NLP_test.csv


In [ ]:
df1= pd.read_csv("Corona_NLP_test.csv",encoding='latin-1')

In [ ]:
df1.head()

UserName  ...           Sentiment
0         1  ...  Extremely Negative
1         2  ...            Positive
2         3  ...  Extremely Positive
3         4  ...            Negative
4         5  ...             Neutral

[5 rows x 6 columns]

In [ ]:

org_tweet= df1['OriginalTweet']
org_tweet

0       TRENDING: New Yorkers encounter empty supermar...
1       When I couldn't find hand sanitizer at Fred Me...
2       Find out how you can protect yourself and love...
3       #Panic buying hits #NewYork City as anxious sh...
4       #toiletpaper #dunnypaper #coronavirus #coronav...
                              ...                        
3793    Meanwhile In A Supermarket in Israel -- People...
3794    Did you panic buy a lot of non-perishable item...
3795    Asst Prof of Economics @cconces was on @NBCPhi...
3796    Gov need to do somethings instead of biar je r...
3797    I and @ForestandPaper members are committed to...
Name: OriginalTweet, Length: 3798, dtype: object

In [ ]:
new_pred = text_clf.predict(org_tweet)

In [ ]:
org_tweet[17]

'When youÂ\x92re stockpiling food &amp; other supplies, buy extra for your local food bank. Many families donÂ\x92t have the luxury to spend beyond their weekly budget. @DailyBreadTO  #coronavirus'

In [ ]:
new_pred[17]

'Negative'

In [ ]:
newy_test = df1['Sentiment']
newy_test

In [ ]:
print(confusion_matrix(newy_test,new_pred))

[[303   6 218  21  44]
 [  8 362  15  15 199]
 [187  47 442 140 225]
 [ 17  14  93 370 125]
 [ 35 202 153  86 471]]


In [ ]:
print(classification_report(newy_test,new_pred))

                    precision    recall  f1-score   support

Extremely Negative       0.55      0.51      0.53       592
Extremely Positive       0.57      0.60      0.59       599
          Negative       0.48      0.42      0.45      1041
           Neutral       0.59      0.60      0.59       619
          Positive       0.44      0.50      0.47       947

          accuracy                           0.51      3798
         macro avg       0.53      0.53      0.53      3798
      weighted avg       0.51      0.51      0.51      3798



In [ ]:
print(accuracy_score(newy_test,new_pred))

0.5129015271195366
