<a href="https://colab.research.google.com/github/sivaramanrajagopal/myNLP60dayprogress/blob/main/Day27_07032022_NLP_Topic_modelling_NMF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
upload=files.upload()

Saving closebro_clean.csv to closebro_clean.csv


In [4]:
df= pd.read_csv("closebro_clean.csv",sep ='\t')

In [5]:
df.head()

Reviews
0  I ringed them for 40 min i was I wait…
1      Cant remember the last time i was…
2                        Awful experience
3                                 Avoid."
4                      Very disappointing

In [6]:
len(df)


4624

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
cv = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [11]:
dtm=cv.fit_transform(df['Reviews'])

In [12]:
dtm

<4624x72 sparse matrix of type '<class 'numpy.float64'>'
	with 16093 stored elements in Compressed Sparse Row format>

In [13]:
from sklearn.decomposition import NMF

In [14]:
NMF_model = NMF(n_components=3,random_state=42)

In [15]:
NMF_model.fit(dtm)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


NMF(n_components=3, random_state=42)

In [16]:
(cv.get_feature_names())[40]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'pay'

In [17]:
import random
rand_in = random.randint(0,50)
cv.get_feature_names()[rand_in]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'credit'

In [19]:
len(NMF_model.components_)

3

In [20]:
first_topic = NMF_model.components_[0]

In [21]:
first_topic.argsort()

array([35, 29, 31, 32, 34, 70, 36, 37, 39, 42, 44, 27, 45, 47, 49, 50, 52,
       59, 61, 62, 63, 64, 69, 46, 26, 71, 18, 12,  6, 11, 10, 25, 16, 17,
       13,  9,  3, 21,  8, 22,  1, 19, 55, 67, 53, 15, 56, 33, 51, 38, 65,
        0, 60, 48, 40,  5, 54,  2, 20, 30,  7, 23, 24, 14, 41, 28,  4, 58,
       43, 57, 68, 66])

In [ ]:
first_topic.argsort()[-10:]

array([69,  1, 36, 50, 26, 45, 13, 39, 52, 18])

In [ ]:
top10words = first_topic.argsort()[-10:]

In [ ]:
for index in top10words:
  print(cv.get_feature_names()[index])

wish
absolute
individuals
reviews
dealing
read
care
morals
ruthless
company


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [22]:
for i,topic in enumerate(NMF_model.components_):
  print(f"THE TOP 15 WORDS IN THIS TOPIC ARE #{i}")
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')

THE TOP 15 WORDS IN THIS TOPIC ARE #0
['account', 'couldn', 'experience', 'awful', 'date', 'days', 'changed', 'payment', 'disappointing', 'atention', 'terrible', 'poor', 'stupid', 'website', 'warning']


THE TOP 15 WORDS IN THIS TOPIC ARE #1
['fraud', 'brother', 'company', 'compny', 'recomend', 'impossible', 'touch', 'crooks', 'worst', 'plague', 'like', 'close', 'brothers', 'finance', 'avoid']


THE TOP 15 WORDS IN THIS TOPIC ARE #2
['thanks', 'fraud', 'brother', 'individuals', 'care', 'ruthless', 'read', 'dealing', 'absolute', 'reviews', 'wish', 'morals', 'disgusting', 'trust', 'company']




/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [23]:
dtm

<4624x72 sparse matrix of type '<class 'numpy.float64'>'
	with 16093 stored elements in Compressed Sparse Row format>

In [26]:
topic_results = NMF_model.transform(dtm)

In [27]:
topic_results[0].round(2)

array([0., 0., 0.])

In [28]:
topic_results[0].argmax()

1

In [29]:
df['Topic'] = topic_results.argmax(axis=1)

In [30]:
df

Reviews  Topic
0       I ringed them for 40 min i was I wait…      1
1           Cant remember the last time i was…      2
2                             Awful experience      2
3                                      Avoid."      1
4                           Very disappointing      0
...                                        ...    ...
4619               Couldn’t even setup account      1
4620                     AVOID LIKE THE PLAGUE      1
4621  never recomend finance from this compny…      1
4622      Changed my payment date to two days…      0
4623                   Waste of Space scammers      1

[4624 rows x 2 columns]

In [33]:
mytopic_dict = {0:'Customer-srvice',1:'payment',2:'fake'}
df['Topic Label'] = df['Topic'].map(mytopic_dict)
df


Reviews  Topic      Topic Label
0       I ringed them for 40 min i was I wait…      1          payment
1           Cant remember the last time i was…      2             fake
2                             Awful experience      2             fake
3                                      Avoid."      1          payment
4                           Very disappointing      0  Customer-srvice
...                                        ...    ...              ...
4619               Couldn’t even setup account      1          payment
4620                     AVOID LIKE THE PLAGUE      1          payment
4621  never recomend finance from this compny…      1          payment
4622      Changed my payment date to two days…      0  Customer-srvice
4623                   Waste of Space scammers      1          payment

[4624 rows x 3 columns]