<a href="https://colab.research.google.com/github/sivaramanrajagopal/myNLP60dayprogress/blob/main/Day26_06032022_NLP_Topic_modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
upload=files.upload()

Saving closebro_clean.csv to closebro_clean.csv


In [3]:
df= pd.read_csv("closebro_clean.csv",sep ='\t')

In [4]:
df.head()

Reviews
0  I ringed them for 40 min i was I wait…
1      Cant remember the last time i was…
2                        Awful experience
3                                 Avoid."
4                      Very disappointing

In [5]:
len(df)


4624

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [9]:
dtm=cv.fit_transform(df['Reviews'])

In [10]:
dtm

<4624x72 sparse matrix of type '<class 'numpy.int64'>'
	with 16093 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.decomposition import LatentDirichletAllocation

In [33]:
LDA = LatentDirichletAllocation(n_components=3,random_state=42)

In [34]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=3, random_state=42)

In [35]:
(cv.get_feature_names())[40]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'pay'

In [37]:
import random
rand_in = random.randint(0,50)
cv.get_feature_names()[rand_in]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'poor'

In [38]:
len(LDA.components_)

3

In [39]:
first_topic = LDA.components_[0]

In [40]:
first_topic.argsort()

array([32,  9, 34, 21, 49, 12, 11, 44,  8, 25, 63, 64, 27,  3, 70, 17, 38,
       51,  0, 65, 10, 16, 58, 43, 55, 67, 53, 20, 54,  2, 19, 46, 71, 22,
       35, 61, 68, 57, 56, 15, 59, 42, 37, 31, 47, 48, 60,  6, 28, 66, 62,
        4, 33, 29, 30,  7, 40,  5, 14, 23, 24, 41, 69,  1, 36, 50, 26, 45,
       13, 39, 52, 18])

In [41]:
first_topic.argsort()[-10:]

array([69,  1, 36, 50, 26, 45, 13, 39, 52, 18])

In [42]:
top10words = first_topic.argsort()[-10:]

In [43]:
for index in top10words:
  print(cv.get_feature_names()[index])

wish
absolute
individuals
reviews
dealing
read
care
morals
ruthless
company


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [44]:
for i,topic in enumerate(LDA.components_):
  print(f"THE TOP 15 WORDS IN THIS TOPIC ARE #{i}")
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')

THE TOP 15 WORDS IN THIS TOPIC ARE #0
['attention', 'changed', 'date', 'days', 'payment', 'wish', 'absolute', 'individuals', 'reviews', 'dealing', 'read', 'care', 'morals', 'ruthless', 'company']


THE TOP 15 WORDS IN THIS TOPIC ARE #1
['recomend', 'compny', 'setup', 'couldn', 'account', 'waste', 'scammers', 'space', 'poor', 'terrible', 'wait', 'ringed', 'min', '40', 'website']


THE TOP 15 WORDS IN THIS TOPIC ARE #2
['witness', 'credit', 'dealer', 'debt', 'report', 'hold', 'thanks', 'warning', 'fraud', 'brother', 'finance', 'company', 'avoid', 'close', 'brothers']




/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [45]:
dtm

<4624x72 sparse matrix of type '<class 'numpy.int64'>'
	with 16093 stored elements in Compressed Sparse Row format>

In [46]:
topic_results = LDA.transform(dtm)

In [47]:
topic_results[0].round(2)

array([0.07, 0.87, 0.07])

In [48]:
topic_results[0].argmax()

1

In [49]:
df['Topic'] = topic_results.argmax(axis=1)

In [50]:
df

Reviews  Topic
0       I ringed them for 40 min i was I wait…      1
1           Cant remember the last time i was…      2
2                             Awful experience      0
3                                      Avoid."      2
4                           Very disappointing      1
...                                        ...    ...
4619               Couldn’t even setup account      1
4620                     AVOID LIKE THE PLAGUE      2
4621  never recomend finance from this compny…      1
4622      Changed my payment date to two days…      0
4623                   Waste of Space scammers      1

[4624 rows x 2 columns]