<a href="https://colab.research.google.com/github/sivaramanrajagopal/myNLP60dayprogress/blob/main/Day28_07032022_NLP_Topic_modelling_QUORA_NMF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
upload=files.upload()

Saving quora_questions.csv to quora_questions.csv


In [3]:
df= pd.read_csv("quora_questions.csv",sep ='\t')

In [4]:
df.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

In [5]:
len(df)


404289

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
cv = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [8]:
dtm=cv.fit_transform(df['Question'])

In [9]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import NMF

In [11]:
NMF_model = NMF(n_components=3,random_state=42)

In [12]:
NMF_model.fit(dtm)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


NMF(n_components=3, random_state=42)

In [13]:
(cv.get_feature_names())[40]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'100000000'

In [14]:
import random
rand_in = random.randint(0,50)
cv.get_feature_names()[rand_in]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'002'

In [15]:
len(NMF_model.components_)

3

In [16]:
first_topic = NMF_model.components_[0]

In [17]:
first_topic.argsort()

array([33767, 17072, 17071, ..., 20023, 37515,  4632])

In [18]:
first_topic.argsort()[-10:]

array([37520, 19824, 22925, 27370,  5268,  5283, 17507, 20023, 37515,
        4632])

In [19]:
top10words = first_topic.argsort()[-10:]

In [20]:
for index in top10words:
  print(cv.get_feature_names()[index])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ways
language
movies
programming
book
books
india
learn
way
best


In [21]:
for i,topic in enumerate(NMF_model.components_):
  print(f"THE TOP 15 WORDS IN THIS TOPIC ARE #{i}")
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')

THE TOP 15 WORDS IN THIS TOPIC ARE #0


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['time', 'online', 'weight', '2016', 'english', 'ways', 'language', 'movies', 'programming', 'book', 'books', 'india', 'learn', 'way', 'best']


THE TOP 15 WORDS IN THIS TOPIC ARE #1
['love', 'trump', 'time', 'good', 'earn', 'work', 'india', 'feel', 'life', 'online', 'mean', 'like', 'make', 'money', 'does']


THE TOP 15 WORDS IN THIS TOPIC ARE #2
['use', 'know', 'think', 'improvement', 'delete', 'easily', 'asked', 'google', 'answer', 'answers', 'ask', 'question', 'questions', 'people', 'quora']




In [22]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

In [23]:
topic_results = NMF_model.transform(dtm)

In [24]:
topic_results[0].round(2)

array([0., 0., 0.])

In [25]:
topic_results[0].argmax()

1

In [26]:
df['Topic'] = topic_results.argmax(axis=1)

In [27]:
df

Question  Topic
0       What is the step by step guide to invest in sh...      1
1       What is the story of Kohinoor (Koh-i-Noor) Dia...      0
2       How can I increase the speed of my internet co...      1
3       Why am I mentally very lonely? How can I solve...      1
4       Which one dissolve in water quikly sugar, salt...      1
...                                                   ...    ...
404284  How many keywords are there in the Racket prog...      0
404285          Do you believe there is life after death?      1
404286                                  What is one coin?      1
404287  What is the approx annual cost of living while...      1
404288              What is like to have sex with cousin?      1

[404289 rows x 2 columns]

In [29]:
mytopic_dict = {0:'Awesomebooks',1:'Country',2:'fake'}
df['Topic Label'] = df['Topic'].map(mytopic_dict)
df


Question  Topic   Topic Label
0       What is the step by step guide to invest in sh...      1       Country
1       What is the story of Kohinoor (Koh-i-Noor) Dia...      0  Awesomebooks
2       How can I increase the speed of my internet co...      1       Country
3       Why am I mentally very lonely? How can I solve...      1       Country
4       Which one dissolve in water quikly sugar, salt...      1       Country
...                                                   ...    ...           ...
404284  How many keywords are there in the Racket prog...      0  Awesomebooks
404285          Do you believe there is life after death?      1       Country
404286                                  What is one coin?      1       Country
404287  What is the approx annual cost of living while...      1       Country
404288              What is like to have sex with cousin?      1       Country

[404289 rows x 3 columns]